# LOGGING
logging:
  file: target/home-on.log
  level:
    org.home.on: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
  liquibase: INFO

# DATABASE
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 9090
    driverClassName: org.postgresql.Driver
    hikari:
        connection-test-query: SELECT 1 FROM DUAL
        pool-name: homeon
        minimum-idle: 1
        idle-timeout: 10000
        maximum-pool-size: 5
  devtools: 
    restart: 
      trigger-file: .reloadtrigger
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties: 
      hibernate:
        format_sql: false
        temp: 
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect               
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/changelog-master.xml
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres

# SECURITY
security:
  password:
    secret: secret

