# LOGGING
logging:
  file: target/home-on.log
  level:
    org.home.on: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
  liquibase: INFO

# DATABASE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: openerp
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties: 
      hibernate:
        format_sql: true
        temp: 
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect               
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/changelog-master.xml
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres

# SECURITY
security:
  password:
    secret: secret


