# LOGGING
logging:
  file: target/home-on.log
  level:
    org.home.on: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
  liquibase: INFO

# DATABASE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 9090
    driverClassName: org.postgresql.Driver
  devtools: 
    restart: 
      trigger-file: .reloadtrigger
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties: 
      hibernate:
        format_sql: false
        temp: 
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect               
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/changelog-master.xml
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres

# SECURITY
security:
  password: 
    secret: secret

