# LOGGING
logging:
  file: target/log/home-on.log
  level:
    org.home.on: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
  liquibase: INFO

# DATABASE
spring:
  web:
    resources:
      static-locations: classpath:/webapp
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 9090
    driverClassName: org.postgresql.Driver
  devtools: 
    restart: 
      trigger-file: .reloadtrigger
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties: 
      hibernate:
        format_sql: true
        temp: 
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect               
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/changelog-master.xml
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres

# SECURITY
security:
  password: 
    secret: secret

# SERVER MQTT
mqtt: 
  enabled: true 
#  url: tcp://broker.mqtt-dashboard.com:1883
#  url: tcp://broker.hivemq.com:1883
#  url: tcp://broker.emqx.io:1883
#  url: tcp://broker.mqttdashboard.com:1883
#  url: tcp://mqtt-dashboard.com:1883
  url: tcp://localhost:1883
  user: caiosilva
  password: 506070
